### ISSUE TITLE
Different spec that supports full GivenWhenThen syntax

### ISSUE THREAD

**Issue by stefanooldeman** [kpn/pyrandall#4]
> Given-When-Then is a style of representing tests - or as its advocates would say - specifying a system's behavior using SpecificationByExample. [see Martin Fowler blog](https://martinfowler.com/bliki/GivenWhenThen.html)

When pyrandall runs a simulates or validates command it will print progress and possible success / failure to stdout.

The default verbosity should still be descriptive enough to pinpoint a issues to a misbehaving component, better said; a requirement on the architecture under test. Currenlty there are two levels of descriptions. (per feature and per scenario) see [examples/scenarios/v2.yaml](https://github.com/kpn/pyrandall/blob/master/examples/scenarios/v2.yaml#L21)

The aim is to add schema properties under `simulate` and `validate`. And preferably to extend the schema/v2 with BDD vocabulary taken from `Given-When-Then` for example:
```
Feature: catalog change events leads to manipulating the nr of items in stock
 Scenario:  A product sale event decrements the stock by one
    Given: product {xyz} has 5 items in stock 
      And: product {foo} has 10 items in stock
    When: a sale event with id {xyz} is processed
    Then: the stock of product {xyz} is 4
      And: the stock of product {foo} is 10
```

Here follow a few examples of the of a spec example schema:

Example 1:
```yaml
version: example-1/v1
feature: catalog change events leads to manipulating the nr of items in stock
scenarios:
  - scenario: "A product sale event decrements the stock by one"
    given-state:
      - description: "product {xyz} has 5 items in stock"
          properties: {}
    when-simulate:  # previously _simulate_ holds one object, now a list
      - that: "a sale event with id {xyz}"
          adapter: broker/kafka
    then-validate:
      - that: "the stock of product {xyz} is 4
         adapter: requests/http
```

Example 2:
```yaml
version: example-1/v1
feature: catalog change events leads to manipulating the nr of items in stock
scenarios:
  - scenario: "A product sale event decrements the stock by one"
    given:
      # the given property can describe the intial state for the application
      # dummy date should be populated as a result of it)
      - description: "product {xyz} has 5 items in stock"
        properties: {}
    when:  # previously _simulate_ holds one object, now a list
      - simulate: "a sale event with id {xyz}"
        adapter: broker/kafka
      - simulate: "a sale event with id {xyz}"
        adapter: requests/http
    then:
      - validate: "the stock of product {xyz} is 4"
        adapter: requests/http
      - validate: "the stock of product {xyz} is 4"
        adapter: requests/http

```
